// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"
import rpc "github.com/7joe7/csvstreamtest/common/rpc"

// ImporterClient is an autogenerated mock type for the ImporterClient type
type ImporterClient struct {
	mock.Mock
}

// ImportClients provides a mock function with given fields: ctx, opts
func (_m *ImporterClient) ImportClients(ctx context.Context, opts ...grpc.CallOption) (rpc.Importer_ImportClientsClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 rpc.Importer_ImportClientsClient
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) rpc.Importer_ImportClientsClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rpc.Importer_ImportClientsClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
