// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// importSrc is an autogenerated mock type for the importSrc type
type ImportSrc struct {
	mock.Mock
}

// ImportCSV provides a mock function with given fields: reader
func (_m *ImportSrc) ImportCSV(reader io.Reader) error {
	ret := _m.Called(reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = rf(reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ImportTar provides a mock function with given fields: reader
func (_m *ImportSrc) ImportTar(reader io.Reader) error {
	ret := _m.Called(reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = rf(reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
